#!/bin/sh

set -eu


err() {
    >&2 echo $@
}

help() {
    echo "
Manage sub git repositories from an .unrealmodules file

    usage: $(basename $0) [SUBCOMMAND] <PATH>

Available subcommands

    clone   - clone new git repositories from .unrealmodules
    commit  - commit changes from sub repositories
    restore - restore .git files for the .unrealmodules
    help    - show this help

Add PATH to execute command to a single sub repository

Format of the .unrealmodules

    Each line has following format

        [PATH]|[GIT_SOURCE]|<BRANCH>

    Example

        path/in/the/repo|https://github.com/epeli/git-unrealmodule|master
        # This line is a comment
        something/else|https://github.com/epeli/redux-render-prop

    The branch is optional

For more information see https://github.com/epeli/git-unrealmodule

"
}

if [ "${1:-}" = "" ]; then
    >&2 help
    exit 1
fi

if [ "${1:-}" = "help" -o  "${1:-}" = "-h" -o  "${1:-}" = "--help" ]; then
    help
    exit
fi

command="$1"
explicit_path="${2:-}"
explicit_path="${explicit_path%/}" # remove trailing slash
root="$(pwd)"


if [ "$(git rev-parse --is-inside-work-tree)" != "true" ]; then
    err "Not inside of a git repository"
    exit 1
fi

if [ ! -f .unrealmodules ]; then
    err "Cannot find .unrealmodules from $(pwd)"
    exit 1
fi

# https://www.shellscript.sh/trap.html
trap cleanup 0 1 2 3 6

cleanup() {
    rm -fr /tmp/*-unrealmodule
}

# Allow comment lines starting with hash
module_config_file=$(mktemp --suffix -unrealmodule)
cat .unrealmodules | sed '/^ *#/ d' > "$module_config_file"

error_messages=""

add_error() {
    error_messages="$error_messages\n\n$@"
}

clone_module() {
    path="$1"
    src="$2"
    branch="${3:-}"

    if [ -d "$path" -a -d "$path/.git" ]; then
        err "Clone already OK: $path"
        return
    fi

    if [ -e "$path" ]; then
        add_error "Cannot clone repository to path $path: already exits"
    fi

    git clone "$src" "$path"

    if [ "$branch" != "" ]; then
        cd "$path"
        git checkout -t "origin/$branch"
        cd -
    fi
}

restore_module() {
    path="$1"
    src="$2"
    branch="${3:-}"

    if [ ! -d "$path" ]; then
        add_error "Cannot restore: $path is not a directory"
        return
    fi

    if [ -d "$path/.git" ]; then
        err "Restore already OK: $path"
        return
    fi

    tmp="$(mktemp -d --suffix -unrealmodule)"
    git clone "$src" "$tmp"
    if [ "$branch" != "" ]; then
        cd "$tmp"
        git checkout -t "origin/$branch"
        cd -
    fi

    mv "$tmp/.git" "$path"
    rm -rf "$tmp"

}

commit_module() {
    path="$1"
    src="$2"

    if [ "$(git diff --cached)" != "" ]; then
        err "You have files in staging area. Cannot continue."
        exit 1
    fi


    if [ ! -d "$path" ]; then
        add_error "Cannot commit: $path: Not a directory"
        return
    fi

    cd "$path"

    if [ ! -d .git ]; then
        add_error "Cannot commit: $path: Not a sub git repository"
        return
    fi

    if [ "$(git status --porcelain)" != "" ]; then
        add_error "Cannot commit: $path: Is dirty. Commit or reset the changes in it first"
        return
    fi

    commit_message="$(git log -1)"
    commit_rev="$(git rev-parse HEAD | head -c 7)"
    real_branch="$(git rev-parse --abbrev-ref HEAD)"

    cd "$root"

    git add "$path/"
    git commit -m "Commit unrealmodule $path to $commit_rev

Origin: $src
Branch: $real_branch

Commit in origin:

$commit_message
"
}

dispatch_command() {
    if [ "$command" = "clone" ]; then
        clone_module $@
    elif [ "$command" = "commit" ]; then
        commit_module $@
    elif [ "$command" = "restore" ]; then
        restore_module $@
    else
        err "Unknown unrealmodule command: $command"
        exit 1
    fi
}

explicit_path_matched=

while read module_line; do
    cd "$root"
    path="$(echo "$module_line" | cut -d "|" -f 1)"
    src="$(echo "$module_line" | cut -d "|" -f 2)"
    branch="$(echo "$module_line" | cut -d "|" -f 3)"
    path="${path%/}" # remove trailing slash

    # err "path:$path src:$src branch:$branch"

    if [ "$explicit_path" != "" ]; then
        if [ "$(realpath "$explicit_path")" =  "$(realpath "$path")" ]; then
            explicit_path_matched="1"
            dispatch_command "$path" "$src" "$branch"
        fi
    else
        dispatch_command "$path" "$src" "$branch"
    fi
done < "$module_config_file"

if [ "$explicit_path" != "" -a "$explicit_path_matched" != "1" ]; then
    err "$explicit_path does match with any repositories in .unrealmodules"
    exit 1
fi

if [ "$error_messages" != "" ]; then
    err
    err "Failed with following errors:"
    err "$error_messages"
    err
    exit 1
fi


