#!/bin/sh

set -eu


command="$1"
root="$(pwd)"

err() {
    >&2 echo $@
}

if [ "$(git rev-parse --is-inside-work-tree)" != "true" ]; then
    err "Not inside of a git repository"
    exit 1
fi

if [ ! -f .unrealmodules ]; then
    err "Cannot find .unrealmodules from $(pwd)"
    exit 1
fi

# Allow comment lines starting with hash
module_config="$(cat .unrealmodules | sed '/^ *#/ d')"

error_messages=""

add_error() {
    error_messages="$error_messages\n\n$@"
}

init_module() {
    path="$1"
    src="$2"
    branch="${3:-}"

    if [ -d "$path" -a -d "$path/.git" ]; then
        err "Init already OK: $path"
        return
    fi

    if [ -e "$path" ]; then
        add_error "Cannot init path $path: already exits"
    fi

    git clone "$src" "$path"

    if [ "$branch" != "" ]; then
        cd "$path"
        git checkout -t "origin/$branch"
        cd -
    fi
}

restore_module() {
    path="$1"
    src="$2"
    branch="${3:-}"

    if [ ! -d "$path" ]; then
        add_error "Cannot restore: $path is not a directory"
        return
    fi

    if [ -d "$path/.git" ]; then
        err "Restore already OK: $path"
        return
    fi

    tmp="$(mktemp -d --suffix -unrealmodule)"
    git clone "$src" "$tmp"
    if [ "$branch" != "" ]; then
        cd "$tmp"
        git checkout -t "origin/$branch"
        cd -
    fi

    mv "$tmp/.git" "$path"
    rm -rf "$tmp"

}

commit_module() {
    path="$1"
    src="$2"

    if [ "$(git diff --cached)" != "" ]; then
        err "You have files in staging area. Cannot continue."
        exit 1
    fi


    if [ ! -d "$path" ]; then
        add_error "Cannot commit: $path: Not a directory"
        return
    fi

    cd "$path"

    if [ ! -d .git ]; then
        add_error "Cannot commit: $path: Not a sub git repository"
        return
    fi

    if [ "$(git status --porcelain)" != "" ]; then
        add_error "Cannot commit: $path: Is dirty. Commit changes in it first"
        return
    fi

    commit_message="$(git log -1)"
    commit_rev="$(git rev-parse HEAD | head -c 7)"
    real_branch="$(git rev-parse --abbrev-ref HEAD)"

    cd "$root"

    git add "$path/"
    git commit -m "Commit unrealmodule $path to $commit_rev

Origin: $src
Branch: $real_branch

Commit in origin:

$commit_message
"
}


echo "$module_config" |
while read module_line; do
    cd "$root"
    path="$(echo "$module_line" | cut -d "|" -f 1)"
    src="$(echo "$module_line" | cut -d "|" -f 2)"
    branch="$(echo "$module_line" | cut -d "|" -f 3)"

    path="${path%/}" # remove trailing slash

    if [ "$command" = "init" ]; then
        init_module "$path" "$src" "$branch"
    elif [ "$command" = "commit" ]; then
        commit_module "$path" "$src" "$branch"
    elif [ "$command" = "restore" ]; then
        restore_module "$path" "$src" "$branch"
    fi


done



if [ "$error_messages" != "" ]; then
    err
    err "Failed with following errors:"
    err "$error_messages"
    err
    exit 1
fi


